server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: api-service
          __path__: /api_data/perf.log
  # - job_name: varlogs
  #   static_configs:
  #     - targets: [localhost]
  #       labels:
  #         job: varlogs
  #         __path__: /var/log/*log
